import React, { useState } from 'react';
import {
  Modal,
  Form,
  Input,
  Select,
  Button,
  message,
  Row,
  Col,
  Divider
} from 'antd';
import { PlusOutlined } from '@ant-design/icons';
import { clientPositionsApi } from '../../lib/supabase/api';
import type { ClientPosition } from '../../lib/supabase/types';

const { TextArea } = Input;
const { Option } = Select;

interface ClientPositionFormProps {
  tenderId: string;
  visible: boolean;
  onCancel: () => void;
  onSuccess: (position: ClientPosition) => void;
  editingPosition?: ClientPosition | null;
}

interface FormData {
  title: string;
  description?: string;
  category?: string;
  priority?: number;
  status?: 'active' | 'inactive' | 'completed';
}

const ClientPositionForm: React.FC<ClientPositionFormProps> = ({
  tenderId,
  visible,
  onCancel,
  onSuccess,
  editingPosition
}) => {
  const [form] = Form.useForm<FormData>();
  const [loading, setLoading] = useState(false);

  const isEditing = !!editingPosition;

  React.useEffect(() => {
    if (visible && editingPosition) {
      form.setFieldsValue({
        title: editingPosition.title,
        description: editingPosition.description || '',
        category: editingPosition.category || '',
        priority: editingPosition.priority || 0,
        status: editingPosition.status || 'active'
      });
    } else if (visible) {
      form.resetFields();
    }
  }, [visible, editingPosition, form]);

  const handleSubmit = async (values: FormData) => {
    setLoading(true);

    try {
      if (isEditing && editingPosition) {
        const result = await clientPositionsApi.update(editingPosition.id, values);
        if (result.error) {
          throw new Error(result.error);
        }
        message.success('Позиция заказчика обновлена');
        onSuccess(result.data!);
      } else {
        const positionData = {
          ...values,
          tender_id: tenderId,
          position_number: 0 // Will be auto-generated by database
        };
        
        const result = await clientPositionsApi.create(positionData);
        if (result.error) {
          throw new Error(result.error);
        }
        message.success('Позиция заказчика создана');
        onSuccess(result.data!);
      }
      
      form.resetFields();
    } catch (error) {
      message.error(`Ошибка: ${error}`);
      console.error('Position form error:', error);
    } finally {
      setLoading(false);
    }
  };

  const handleCancel = () => {
    form.resetFields();
    onCancel();
  };

  return (
    <Modal
      title={isEditing ? 'Редактировать позицию заказчика' : 'Добавить позицию заказчика'}
      open={visible}
      onCancel={handleCancel}
      footer={null}
      width={700}
      destroyOnClose
    >
      <Form
        form={form}
        layout="vertical"
        onFinish={handleSubmit}
        className="mt-4"
      >
        <Row gutter={16}>
          <Col span={16}>
            <Form.Item
              name="title"
              label="Название позиции"
              rules={[
                { required: true, message: 'Введите название позиции' },
                { min: 3, message: 'Название должно содержать минимум 3 символа' }
              ]}
            >
              <Input 
                placeholder="Например: Фундаментные работы"
                maxLength={200}
              />
            </Form.Item>
          </Col>
          
          <Col span={8}>
            <Form.Item
              name="category"
              label="Категория"
            >
              <Select 
                placeholder="Выберите категорию"
                allowClear
              >
                <Option value="строительство">Строительство</Option>
                <Option value="материалы">Материалы</Option>
                <Option value="оборудование">Оборудование</Option>
                <Option value="проектирование">Проектирование</Option>
                <Option value="монтаж">Монтаж</Option>
                <Option value="отделка">Отделка</Option>
                <Option value="инженерные системы">Инженерные системы</Option>
                <Option value="прочее">Прочее</Option>
              </Select>
            </Form.Item>
          </Col>
        </Row>

        <Form.Item
          name="description"
          label="Описание позиции"
        >
          <TextArea 
            rows={3}
            placeholder="Подробное описание работ или материалов в данной позиции"
            maxLength={1000}
            showCount
          />
        </Form.Item>

        <Row gutter={16}>
          <Col span={12}>
            <Form.Item
              name="priority"
              label="Приоритет"
              initialValue={0}
            >
              <Select>
                <Option value={0}>Обычный</Option>
                <Option value={1}>Высокий</Option>
                <Option value={2}>Критический</Option>
              </Select>
            </Form.Item>
          </Col>
          
          <Col span={12}>
            <Form.Item
              name="status"
              label="Статус"
              initialValue="active"
            >
              <Select>
                <Option value="active">Активна</Option>
                <Option value="inactive">Неактивна</Option>
                <Option value="completed">Завершена</Option>
              </Select>
            </Form.Item>
          </Col>
        </Row>

        <Divider />

        <div className="flex justify-end gap-2">
          <Button onClick={handleCancel}>
            Отмена
          </Button>
          <Button 
            type="primary" 
            htmlType="submit"
            loading={loading}
            icon={<PlusOutlined />}
          >
            {isEditing ? 'Сохранить изменения' : 'Создать позицию'}
          </Button>
        </div>
      </Form>
    </Modal>
  );
};

export default ClientPositionForm;